---
abstract: 'calculate CPANTS kwalitee score for your dist'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-App-Command-kwalitee
requires:
  App::CPANTS::Lint: '0.03'
  Dist::Zilla::App: '0'
  perl: '5.008003'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/Dist-Zilla-App-Command-kwalitee
  repository: https://github.com/neilbowers/Dist-Zilla-App-Command-kwalitee.git
version: '0.03'
